INSERT INTO product (id, name, description, price, image, quantity, category, sold_out) VALUES
    (1, 'Bananas', 'Fresh yellow bananas, sold per bunch', 1.29, 'bananas.jpg', 100, 'Fruits', false),
    (2, 'Whole Milk', 'Whole milk, 1 gallon', 3.49, 'milk.jpg', 50, 'Dairy', false),
    (3, 'Eggs', 'Large grade A eggs, dozen', 2.99, 'eggs.jpg', 60, 'Dairy', false),
    (4, 'Bread', 'Whole wheat sandwich bread', 2.49, 'bread.jpg', 40, 'Bakery', false),
    (5, 'Chicken Breast', 'Boneless skinless chicken breast, per lb', 4.99, 'chicken.jpg', 30, 'Meat', false),
    (6, 'Apples', 'Honeycrisp apples, per lb', 1.99, 'apples.jpg', 80, 'Fruits', false),
    (7, 'Rice', 'Long grain white rice, 5 lb bag', 6.49, 'rice.jpg', 25, 'Pantry', false),
    (8, 'Coffee', 'Ground medium roast coffee, 12 oz', 8.99, 'coffee.jpg', 35, 'Beverages', false),
    (9, 'Oranges', 'Navel oranges, per lb', 2.49, 'oranges.jpg', 70, 'Fruits', false),
    (10, 'Strawberries', 'Fresh strawberries, 1 lb box', 3.99, 'strawberries.jpg', 40, 'Fruits', false),
    (11, 'Carrots', 'Fresh orange carrots, 2 lb bag', 1.79, 'carrots.jpg', 90, 'Vegetables', false),
    (12, 'Broccoli', 'Fresh broccoli crowns, per lb', 2.29, 'broccoli.jpg', 45, 'Vegetables', false),
    (13, 'Spinach', 'Baby spinach, 5 oz bag', 2.99, 'spinach.jpg', 35, 'Vegetables', false),
    (14, 'Tomatoes', 'Vine-ripened tomatoes, per lb', 2.49, 'tomatoes.jpg', 55, 'Vegetables', false),
    (15, 'Cheddar Cheese', 'Sharp cheddar cheese block, 8 oz', 4.49, 'cheese.jpg', 30, 'Dairy', false),
    (16, 'Greek Yogurt', 'Plain Greek yogurt, 32 oz tub', 5.29, 'yogurt.jpg', 25, 'Dairy', false),
    (17, 'Butter', 'Salted butter, 1 lb', 3.79, 'butter.jpg', 20, 'Dairy', false),
    (18, 'Bagels', 'Plain bagels, pack of 6', 3.29, 'bagels.jpg', 24, 'Bakery', false),
    (19, 'Croissants', 'Butter croissants, pack of 4', 4.49, 'croissants.jpg', 0, 'Bakery', true),
    (20, 'Ground Beef', '80/20 ground beef, per lb', 6.99, 'ground_beef.jpg', 20, 'Meat', false),
    (21, 'Bacon', 'Applewood smoked bacon, 12 oz', 5.99, 'bacon.jpg', 32, 'Meat', false),
    (22, 'Salmon Fillet', 'Fresh Atlantic salmon fillet, per lb', 9.99, 'salmon.jpg', 15, 'Seafood', false),
    (23, 'Shrimp', 'Peeled and deveined shrimp, 1 lb bag', 8.49, 'shrimp.jpg', 20, 'Seafood', false),
    (24, 'Orange Juice', '100% orange juice, 64 oz', 4.29, 'orange_juice.jpg', 40, 'Beverages', false),
    (25, 'Bottled Water', 'Bottled water, 24-pack', 5.49, 'water.jpg', 60, 'Beverages', false),
    (26, 'Potato Chips', 'Classic salted potato chips, family size', 3.49, 'chips.jpg', 50, 'Snacks', false),
    (27, 'Granola Bars', 'Oats and honey granola bars, 12-pack', 4.99, 'granola.jpg', 45, 'Snacks', false);
